<?php

/**
 * Created by PhpStorm.
 * User: JohnnyNguyen
 * Date: 7/2/16
 * Time: 22:58
 */
class CustomFormatter extends CFormatter
{
    public function formatLink($value)
    {
        return '<a href="' . $value . '">' . $value . '</a>';
    }

    public function formatBold($value)
    {
        return '<b>' . $value . '</b>';
    }

    public function formatJson($value)
    {
        $json = $value;
        $result = '';
        $level = 0;
        $in_quotes = false;
        $in_escape = false;
        $ends_line_level = NULL;
        $json_length = strlen( $json );

        for( $i = 0; $i < $json_length; $i++ ) {
            $char = $json[$i];
            $new_line_level = NULL;
            $post = "";
            if( $ends_line_level !== NULL ) {
                $new_line_level = $ends_line_level;
                $ends_line_level = NULL;
            }
            if ( $in_escape ) {
                $in_escape = false;
            } else if( $char === '"' ) {
                $in_quotes = !$in_quotes;
            } else if( ! $in_quotes ) {
                switch( $char ) {
                    case '}': case ']':
                    $level--;
                    $ends_line_level = NULL;
                    $new_line_level = $level;
                    break;

                    case '{': case '[':
                    $level++;
                    case ',':
                        $ends_line_level = $level;
                        break;

                    case ':':
                        $post = " ";
                        break;

                    case " ": case "\t": case "\n": case "\r":
                    $char = "";
                    $ends_line_level = $new_line_level;
                    $new_line_level = NULL;
                    break;
                }
            } else if ( $char === '\\' ) {
                $in_escape = true;
            }
            if( $new_line_level !== NULL ) {
                $result .= "\n".str_repeat( "\t", $new_line_level );
            }
            $result .= $char.$post;
        }

        return $result;
    }

    public function formatArray($value)
    {
        return (is_array($value)) ?
            implode(', ', $value) : $value;
    }

    public function formatDate($value)
    {
        return parent::formatDate($value);
    }

    public function formatTime($value)
    {
        return parent::formatTime($value); // TODO: Change the autogenerated stub
    }
}